export const goods = [
  {
    id: 1,
    name: "roshen",
    weight: "250 г",
    price: "100 грн",
    category: "candy",
    image: "images/images 6.png",
  },
  {
    id: 2,
    name: "cherry",
    weight: "300 г",
    price: "70 грн",
    category: "candy",
    image: "images/images 2.png",
  },
  {
    id: 3,
    name: "jelly",
    weight: "200 г",
    price: "125  грн",
    category: "candy",
    image: "images/images 5.png",
  },
  {
    id: 4,
    name: "chupa-chups",
    weight: "20 г",
    price: "37 грн",
    category: "candy",
    image: "images/images 8.png",
  },
  {
    id: 5,
    name: "chocolate",
    weight: "400 г",
    price: "150 грн",
    category: "cookie",
    image: "images/images 7.png",
  },
  {
    id: 6,
    name: "chocolate-vanilla",
    weight: "450 г",
    price: "196 грн",
    category: "cookie",
    image: "images/images 4.png",
  },
  {
    id: 7,
    name: "vanilla",
    weight: "500 г",
    price: "85 грн",
    category: "cookie",
    image: "images/images 16.png",
  },
  {
    id: 8,
    name: "maria",
    weight: "700 г",
    price: "170 грн",
    category: "cookie",
    image: "images/images 1.png",
  },
  {
    id: 9,
    name: "lemon",
    weight: "80 г",
    price: "40  грн",
    category: "ice-cream",
    image: "images/images 3.png",
  },
  {
    id: 10,
    name: "melon",
    weight: "90 г",
    price: "37 грн",
    category: "ice-cream",
    image: "images/images 11.png",
  },
  {
    id: 11,
    name: "bounty",
    weight: "80 г",
    price: "68 грн",
    category: "ice-cream",
    image: "images/images 15.png",
  },
  {
    id: 12,
    name: "caramel",
    weight: "120 г",
    price: "79 грн",
    category: "ice-cream",
    image: "images/images 9.png",
  },
  {
    id: 13,
    name: "fanta",
    weight: "250 г",
    price: "39 грн",
    category: "water",
    image: "images/images 12.png",
  },
  {
    id: 14,
    name: "coka-cola",
    weight: "500 г",
    price: "72 грн",
    category: "water",
    image: "images/images 14.png",
  },
  {
    id: 15,
    name: "sprite",
    weight: "250 г",
    price: "37 грн",
    category: "water",
    image: "images/images 13.png",
  },
  {
    id: 16,
    name: "mineral",
    weight: "500 г",
    price: "28 грн",
    category: "water",
    image: "images/images 10.png",
  },
];
